### PR TITLE
Use email as username 178177525

### PR DESCRIPTION
**Pull request by esirK**
## Description
By default, Django uses username for user id i.e. login. This PR switches to emails by default.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
## Screenshots

Screenshot 2021-05-28 at 08 46 30

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏾 @esirK .

Looks good but I think there a few things we need to discuss and agree upon before proceeding. (I'm using [Customizing authentication in Django](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/) as my ref).

1. Since we want to change required field to email and leave username as optional (sort of like GitHub, we don't want to completely remove it), I think we should start from [`AbstractBaseUser`](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#specifying-a-custom-user-model) and not `AbstractUser`.
Screenshot from 2021-05-24 08-23-37
2. On ☝🏾 , is it possible to have authentication method that uses either `email` or `username` (if available)?
3. Our ultimate goal is to have user account / profile with 👇🏾  info; Lets think and decide what needs to go into user account model and what will go to user profile model
Screenshot_2021-05-24 Super Fast Visual Sitemap Tool Octopus do
4. ~~`ActnowXXXX`~~`ActNowXXX`
5. Can we use `.` in app names e.g. `actnow.auth` / `actnow.accounts`, etc.?
6. I think the full [example](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#a-full-example) given in the documentation page is a pretty good place to start.

**Comment by esirK** [comment]
@kilemensi  Thank you for the detailed feedback.
>is it possible to have an authentication method that uses either email or username

Yes. We can create our own authentication backend(not a lot of work) that does this.

>Can we use . in app names e.g. actnow.auth / actnow.accounts, etc.?

Sure.

**Comment by esirK** [comment]
Ola @kilemensi 
The functionality has been added and users can log in using either username or email.
 Also, Django doesn't allow us to use app names with `.` in them so we can't have `actnow.accounts`

I don't think the `Profile` bit should be done in this PR. What do you think?

**Comment by kilemensi** [comment]
> Ola @kilemensi
> The functionality has been added and users can log in using either username or email.
> Also, Django doesn't allow us to use app names with `.` in them so we can't have `actnow.accounts`
> 
> I don't think the `Profile` bit should be done in this PR. What do you think?

1. So how do those other apps like `django.contrib` or `allauth.account` do it?
2. Yes Profile isn’t for this PR; we just need to decide what goes into user account (this PR) and what will be implemented in user profile (next PR)

**Comment by esirK** [comment]
> 1. So how do those other apps like `django.contrib` or `allauth.account` do it?

Here is some of their structure.
Screenshot 2021-05-26 at 09 34 31

which is almost what we have. The reason it's not exactly like that is because of how the project was initialized. If this was used `django-admin startproject actnow .` then the folder structure will be/is `actNOW/actnow` and everything else e.g `manage.py`, all apps created using `manage.py` will be in the same level.

To change this, We can manually move the files(Not certain if this will break something) or re-initialize the project without specifying current directory as where all files should be placed.
 
> 2. Yes Profile isn’t for this PR; we just need to decide what goes into user account (this PR) and what will be implemented in user profile (next PR)

For this, I think we can have user account with only what's required for a user to login and move everything else (Firstname, Lastname) e.t.c to the Profile Model.

**Comment by kilemensi** [comment]
Not sure I follow point 1 @esirK . For example this is [`allauth`](https://github.com/pennersr/django-allauth) repo. How is it different from ours?

Point 2 makes sense but doesn't Django include name as part of default user account?

**Comment by esirK** [comment]
> Not sure I follow point 1 @esirK . For example this is [`allauth`](https://github.com/pennersr/django-allauth) repo. How is it different from ours?

I see. I've updated the filestructure. 

> Point 2 makes sense but doesn't Django include the name as part of default user account?

`first_name, last_name` e.t.c are included in the `AbstractUser` class but we are subclassing `AbstractBaseUser` which only has `password, last_login, is_active`

**Comment by esirK** [comment]
I think this is good too @kilemensi  right?

**Review by kilemensi — APPROVED** [review]
🚀

**Pull request merged**
