### PR TITLE
Fix docker compose startup

### PR DESCRIPTION
**Pull request by esirK**
## Description
I observed that migrations were not being automatically applied on **docker-compose up**. on digging further, It turns out the `entrypoint.sh script` that we expected to wait for `postgres` service to be ready wasn't running. Some of the reasons included `DATABASE` environment variable not being set, `netcat` not being installed e.t.c Instead of having to use this method, this PR utilizes docker-compose health checks to ensure that the database is in a state to receive connections before starting up the app service.

Fixes # (issue)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
Looks alright @esirK but entypoint method works even when we're not using docker-compose (dokku in prod, etc.).

What is the plan for that?

**Comment by esirK** [comment]
> Looks alright @esirK but entypoint method works even when we're not using docker-compose (dokku in prod, etc.).
> 
> What is the plan for that?

Ooh. I hadn't thought of that. But I don't think we need it because our database will always be in RDS right? 
Also, I can't see any app that has set the `DATABASE`, `SQL_HOST`, or `$SQL_PORT` environment variables required by the script.

**Comment by kilemensi** [comment]
> > Looks alright @esirK but entypoint method works even when we're not using docker-compose (dokku in prod, etc.).
> > What is the plan for that?
> 
> Ooh. I hadn't thought of that. But I don't think we need it because our database will always be in RDS right?
> Also, I can't see any app that has set the `DATABASE`, `SQL_HOST`, or `$SQL_PORT` environment variables required by the script.

`DATABASE`, `SQL_HOST`, or `$SQL_PORT` are environmental variable that you can set either in `docker-compose.yml` directly, `.env `file (which `docker-compose` command loads automatically), or defined on the instance which we do / should do for `dokku`

May be there is a name-mismatch, check & confirm.

**Comment by esirK** [comment]
> `DATABASE`, `SQL_HOST`, or `$SQL_PORT` are environmental variable that you can set either in `docker-compose.yml` directly, `.env `file (which `docker-compose` command loads automatically), or defined on the instance which we do / should do for `dokku`
> 
> May be there is a name-mismatch, check & confirm.

@kilemensi  I have done some checks (more than 3 apps) and I'm certain we aren't using this bit of code any of them including `sensorsafrica` from which we inherited this piece of code from. IMHO, I think we can drop it in favor of the health checks.

**Pull request merged**
