### PR TITLE
Fix ensure only apps can create users

### PR DESCRIPTION
**Pull request by esirK**
## Description

Ensures only apps can create a user account by sending an application token.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
Screenshot 2021-06-16 at 05 33 29

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏾 @esirK 

Looks good but

1. Application api key/token shouldn't be passed in as part of data (HTTP Authentication header?),
2. What method are we using for authentication?

**Comment by esirK** [comment]
> 👍🏾 @esirK 
> 
> Looks good but
> 
> 1. Application api key/token shouldn't be passed in as part of data (HTTP Authentication header?),
> 2. What method are we using for authentication?

1. I'll update this to send in the headers
2. We are using session and token authentication from DRF

**Comment by esirK** [comment]
@kilemensi  I've updated the code to use a custom class that uses `JWT Token id` that is only associated with an Application.

**Comment by kilemensi** [comment]
QQ @esirK , where do the JWT stuff come from? OAuth Toolkit?

**Comment by esirK** [comment]
> QQ @esirK , where do the JWT stuff come from? OAuth Toolkit?

Yes.

**Comment by kilemensi** [comment]
> > QQ @esirK , where do the JWT stuff come from? OAuth Toolkit?
> 
> Yes.

Not sure if it was intended to be used like this @esirK . Do you have any doc I can checkout?

**Comment by esirK** [comment]
> > > QQ @esirK , where do the JWT stuff come from? OAuth Toolkit?
> > 
> > 
> > Yes.
> 
> Not sure if it was intended to be used like this @esirK . Do you have any doc I can checkout?

I agree. It might have not been intended to be used like this but I think `Application` too wasn't meant to be used/treated as a user i.e used for authorization.  So we are just trying to hack it to work as a user. I haven't seen a doc that tries to use `Application` for authorization yet.

**Comment by kilemensi** [comment]
> > > > QQ @esirK , where do the JWT stuff come from? OAuth Toolkit?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Not sure if it was intended to be used like this @esirK . Do you have any doc I can checkout?
> 
> I agree. It might have not been intended to be used like this but I think `Application` too wasn't meant to be used/treated as a user i.e used for authorization. So we are just trying to hack it to work as a user. I haven't seen a doc that tries to use `Application` for authorization yet.

If that's the case, then why don't we stop hacking and have "Application" users i.e. users responsible for application tokens? Think of this like when you have to get API key from Airtable or something. You have to register there, right?

1. We an application e.g. PromiseTracker,
2. We need to give application level access to at least one user,

How would this work?

**Comment by esirK** [comment]
> > > > > QQ @esirK , where do the JWT stuff come from? OAuth Toolkit?
> > > > 
> > > > 
> > > > Yes.
> > > 
> > > 
> > > Not sure if it was intended to be used like this @esirK . Do you have any doc I can checkout?
> > 
> > 
> > I agree. It might have not been intended to be used like this but I think `Application` too wasn't meant to be used/treated as a user i.e used for authorization. So we are just trying to hack it to work as a user. I haven't seen a doc that tries to use `Application` for authorization yet.
> 
> If that's the case, then why don't we stop hacking and have "Application" users i.e. users responsible for application tokens? Think of this like when you have to get API key from Airtable or something. You have to register there, right?
> 
> 1. We an application e.g. PromiseTracker,
> 2. We need to give application level access to at least one user,
> 
> How would this work?

Yeah, I think this too Could work. Was actually among the initial suggestions/questions [here](https://code4africa.slack.com/archives/D013D6K4XEC/p1623316578028300?thread_ts=1623313747.028000&cid=D013D6K4XEC)

**Comment by esirK** [comment]
> If that's the case, then why don't we stop hacking and have "Application" users i.e. users responsible for application tokens? Think of this like when you have to get API key from Airtable or something. You have to register there, right?
> 
> 1. We an application e.g. PromiseTracker,
> 2. We need to give application level access to at least one user,
> 
> How would this work?

@kilemensi  
just for confirmation, these `Application` users will be created directly from the dashboard right?
Also, we should limit 1 user to 1 application right?

**Comment by kilemensi** [comment]
> > If that's the case, then why don't we stop hacking and have "Application" users i.e. users responsible for application tokens? Think of this like when you have to get API key from Airtable or something. You have to register there, right?
> > 
> > 1. We an application e.g. PromiseTracker,
> > 2. We need to give application level access to at least one user,
> > 
> > How would this work?
> 
> @kilemensi
> just for confirmation, these `Application` users will be created directly from the dashboard right?

I think if we can create users as part of creating the application will be for the best but if we have to manually create them in the dashboard, then we can live with that.

Similar to Tokens, if application users can request/change Tokens by themselves, that will also be cool, but if they have to ask us (i.e. someone to log into dashboard and create/change the token), then we can live with that too.

**Pull request closed without merging**
