### PR TITLE
Filter by signature signatory user profile

### PR DESCRIPTION
**Pull request by esirK**
## Description

Filter by signature signatory user profile

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

N/A
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — APPROVED** [review]
🚀 

---

Since `signatures__signatory__user_profile` is kind of long, I think using a [`FilterSet`](https://django-filter.readthedocs.io/en/stable/guide/rest_framework.html#adding-a-filterset-with-filterset-class) will allow us to give it a shorter name e.g. just `signatory` or `signatories` if it allow multiple selection.

**Comment by kilemensi** [comment]
PS: This fix is just for petitions signed by users @esirK, what about organisations?

**Comment by esirK** [comment]
> 

@kilemensi  do/should organizations have the ability to sign a petition?

**Comment by kilemensi** [comment]
> > 
> 
> @kilemensi do/should organizations have the ability to sign a petition?

I think so @esirK ... If organisations can create a petition, why wouldn't they be allowed to follow or sign one?

**Comment by esirK** [comment]
@kilemensi  I've added filters for both org and user

**Review by kilemensi — APPROVED** [review]
🚀 

---

Since `owner` and `followers` are all profiles and we don't include _profile in their names, we should do the same for signatories. May be `individual_signatories` and `organisation_signatories`, etc.

**Pull request merged**
