### PR TITLE
Adds user profile api endpoint.

### PR DESCRIPTION
**Pull request by esirK**
## Description

Adds API endpoint for user profile

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
Screenshot 2021-06-15 at 10 49 28

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by esirK** [comment]
@kilemensi  reminder on reviewing this.

**Comment by kilemensi** [comment]
@esirK :

1. `UserAccount` creation: We want to authorize **apps** since users don't exist at this point. Api key seems to be the way forward but still up for discussion,
2. `UserAccount` access: We want to authorize _users_  via OAuth (since they already have accounts by this point),
2. `UserProfile` creation & access: We want to authorize _users_ via OAuth.

So what (and how) are we addressing ☝🏾  in this PR.

**Comment by esirK** [comment]
> @esirK :
> 
> 1. `UserAccount` creation: We want to authorize **apps** since users don't exist at this point. Api key seems to be the way forward but still up for discussion,
> 2. `UserAccount` access: We want to authorize _users_  via OAuth (since they already have accounts by this point),
> 3. `UserProfile` creation & access: We want to authorize _users_ via OAuth.
> 
> So what (and how) are we addressing ☝🏾 in this PR.

This PR was addressing `UserProfile` creation by `Applications` which from your description above seems not to be what is wanted. I'll move the logic to User Registration API.

**Comment by kilemensi** [comment]
> > @esirK :
> > 
> > 1. `UserAccount` creation: We want to authorize **apps** since users don't exist at this point. Api key seems to be the way forward but still up for discussion,
> > 2. `UserAccount` access: We want to authorize _users_  via OAuth (since they already have accounts by this point),
> > 3. `UserProfile` creation & access: We want to authorize _users_ via OAuth.
> > 
> > So what (and how) are we addressing ☝🏾 in this PR.
> 
> This PR was addressing `UserProfile` creation by `Applications` which from your description above seems not to be what is wanted. I'll move the logic to User Registration API.

Oh, cool @esirK ... Once we have users, they should be authorized to do everything themselves.

**Pull request closed without merging**
