### PR TITLE
Ft include user info on authentication

### PR DESCRIPTION
**Pull request by esirK**
## Description

Include user info on successful authentication using OAuth2

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
Screenshot 2022-02-18 at 18 42 56

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏽


———-

On mobile so I could be missing something but I don’t see where we’re handling invalid token e.g. invalid credentials provided.

**Comment by esirK** [comment]
> 
> On mobile so I could be missing something but I don’t see where we’re handling invalid token e.g. invalid credentials provided.

@kilemensi  since we are inheriting from the default `TokenView` and just overriding the `post` method to add new info to the Response(leaving everything else as is), I bet those checks are still being  handled by the `OAuthLibMixin`

**Comment by esirK** [comment]
@kilemensi  anything on this?

**Comment by kilemensi** [comment]
> @kilemensi anything on this?

Nah... Thought it was already approved @esirK

**Review by kilemensi — APPROVED** [review]
🚀

**Pull request merged**
